apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-backend
  labels:
    app: todo-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-back
  template:
    metadata:
      labels:
        app: todo-back
    spec:
      containers:
      - name: toumash-todo-back
        image: toumash/todoapp-back
        env:
        - name: ConnectionStrings__TaskContext
          value: "server=todo-mysql;database=todoapp;user ID=root;password=my-secret-pw;port=3306;"
